serial:
  timeout: 0.5
  baud: 115200
  port: COM5


cargo:
  serial_number: S23417
  path: "data"

azure:
  connection_string:
  container_name: "test"
cameras:
  - camera:
      address: 3
      name: right_left_1
      compression: 34
      resolution: 7
      nightfill: 100
  - camera:
      address: 2
      name: right_left_2
      compression: 34
      resolution: 6
      nightfill: 100


