serial:
  timeout: 0.5
  baud: 115200
  port: COM3


cargo:
  serial_number: S23417
  path: "C:\\Python"

azure:
  connection_string: "DefaultEndpointsProtocol=https;AccountName=rs485;AccountKey=CoJqB9VFTKilKRKunDiLU/BNT/pEgw0fcCY7+GmSvnzur2iJz2A1+J4OZzxC2V7C++8cL7MaaXl8+AStNbDBoQ==;EndpointSuffix=core.windows.net"
  container_name: "test"

cameras:
  - camera:
      address: 3
      name: right_left_1
      compression: 34
      resolution: 7
      nightfill: 100
  - camera:
      address: 2
      name: right_left_2
      compression: 34
      resolution: 6
      nightfill: 100


